// This file is automatic generated by script.  
// DO NOT EDIT DIRECTLY.   

using System;
using Konata.Core.Utils.Protobuf;

namespace Konata.Core.Packets.Oidb.Model
{
    internal abstract class OidbCmd0xed3 : OidbSSOPkg
    {
        internal OidbCmd0xed3(uint svcType, ReqBody reqBody)

            : base(0xed3, svcType, null, (ProtoTreeRoot root) =>
            {
                root.AddTree(reqBody.BuildTree());
            })
        {

        }

        public class ReqBody : OidbStruct
        {
            // 0x08
            public long? to_uin;

            // 0x10
            public long? group_code;

            // 0x18
            public uint? msg_seq;

            // 0x20
            public uint? msg_rand;

            // 0x28
            public long? aio_uin;

            // 0x30
            public uint? nudge_type;

            public override void Write(ProtoTreeRoot root)
            {
                root.AddLeafVar("08", to_uin);
                root.AddLeafVar("10", group_code);
                root.AddLeafVar("18", msg_seq);
                root.AddLeafVar("20", msg_rand);
                root.AddLeafVar("28", aio_uin);
                root.AddLeafVar("30", nudge_type);
            }
        }
    }
}
