// This file is automatic generated by script.  
// DO NOT EDIT DIRECTLY.   

using System;
using Konata.Core.Utils.Protobuf;

namespace Konata.Core.Packets.Oidb.Model
{
    public abstract class OidbCmd0xd50 : OidbSSOPkg
    {
        internal OidbCmd0xd50(uint svcType, ReqBody reqBody)
            : base(0xd50, svcType, null, (ProtoTreeRoot root) =>
            {
                root.AddTree(reqBody.BuildTree());
            })
        {
        }

        public class ExtSnsFrdData : OidbStruct
        {
            // 0x08
            public long? frd_uin;

            // 0xCAB72C
            public byte[] music_switch;

            // 0xCAA831
            public byte[] mutualmark_alienation;

            // 0xCAEC44
            public byte[] mutualmark_score;

            // 0xCADD49
            public byte[] ksing_switch;

            // 0xCAB058
            public byte[] lbs_share;

            public override void Write(ProtoTreeRoot root)
            {
                root.AddLeafVar("08", frd_uin);
                root.AddLeafBytes("CAB72C", music_switch);
                root.AddLeafBytes("CAA831", mutualmark_alienation);
                root.AddLeafBytes("CAEC44", mutualmark_score);
                root.AddLeafBytes("CADD49", ksing_switch);
                root.AddLeafBytes("CAB058", lbs_share);
            }
        }

        public class KSingRelationInfo : OidbStruct
        {
            // 0x08
            public uint? flag;

            public override void Write(ProtoTreeRoot root)
            {
                root.AddLeafVar("08", flag);
            }
        }

        public class ReqBody : OidbStruct
        {
            // 0x08
            public long? appid;

            // 0x10
            public uint? max_pkg_size;

            // 0x18
            public uint? start_time;

            // 0x20
            public uint? start_index;

            // 0x28
            public uint? req_num;

            // 0x30
            public uint? rpt_uin_list;

            // 0xC8B72C
            public uint? req_music_switch;

            // 0xC8A831
            public uint? req_mutualmark_alienation;

            // 0xC8EC44
            public uint? req_mutualmark_score;

            // 0xC8DD49
            public uint? req_ksing_switch;

            // 0xC8B058
            public uint? req_mutualmark_lbsshare;

            public override void Write(ProtoTreeRoot root)
            {
                root.AddLeafVar("08", appid);
                root.AddLeafVar("10", max_pkg_size);
                root.AddLeafVar("18", start_time);
                root.AddLeafVar("20", start_index);
                root.AddLeafVar("28", req_num);
                root.AddLeafVar("30", rpt_uin_list);
                root.AddLeafVar("C8B72C", req_music_switch);
                root.AddLeafVar("C8A831", req_mutualmark_alienation);
                root.AddLeafVar("C8EC44", req_mutualmark_score);
                root.AddLeafVar("C8DD49", req_ksing_switch);
                root.AddLeafVar("C8B058", req_mutualmark_lbsshare);
            }
        }

        public class RspBody : OidbStruct
        {
            // 0x0A
            public byte[] rpt_msg_update_data;

            // 0x58
            public uint? over;

            // 0x60
            public uint? next_start;

            // 0x68
            public uint? rpt_uint64_unfinished_uins;

            public override void Write(ProtoTreeRoot root)
            {
                root.AddLeafBytes("0A", rpt_msg_update_data);
                root.AddLeafVar("58", over);
                root.AddLeafVar("60", next_start);
                root.AddLeafVar("68", rpt_uint64_unfinished_uins);
            }
        }
    }
}
