@echo off

set SOURCE=%2
set TARGET=%SOURCE%Msf\ServiceTouch.cs
echo [PreBuild.ScanService] %TARGET%

:: Remove old file.
echo [PreBuild.ScanService] Clean.
del /f "%TARGET%"

:: Scan folders and generate the new file.
echo [PreBuild.ScanService] Generating service touch file.
echo // This file is automatic generated by script.  >> %TARGET%
echo // DO NOT EDIT DIRECTLY.                        >> %TARGET%
echo.                                                >> %TARGET%
echo using System;                                   >> %TARGET%
echo.                                                >> %TARGET%
echo namespace Konata.Msf                            >> %TARGET%
echo {                                               >> %TARGET%
echo     public abstract partial class Service       >> %TARGET%
echo     {                                           >> %TARGET%
echo         static bool TouchServices()             >> %TARGET%
echo         {                                       >> %TARGET%
echo             Service instance;                   >> %TARGET%

:: Write classes to.
for /r %SOURCE%Msf\Services\ %%f in (*.cs) do (
	call :write %%f
)

echo             return true;                        >> %TARGET%
echo         }                                       >> %TARGET%
echo     }                                           >> %TARGET%
echo }                                               >> %TARGET%

echo [PreBuild.ScanService] Success.
goto :eof

:write
set CLASS=%1
set CLASS=%CLASS:*Msf\=%
set CLASS=%CLASS:.cs=%
set CLASS=%CLASS:\=.%
echo             instance = %CLASS%.Instance;        >> %TARGET%
