#!bin/bash

SOURCE=$2
TARGET=${SOURCE}/ServiceInitial.cs
echo [PreBuild.ScanService] $TARGET

# Remove old file.
echo [PreBuild.ScanService] Clean.
rm $TARGET || true;

# Scan folders and generate the new file.
echo [PreBuild.ScanService] Generating service touch file.
cat > $TARGET << _EOF_
// This file is automatic generated by script.
// DO NOT EDIT DIRECTLY.

using System;
using Konata.Events;

namespace Konata
{
    public partial class ServiceMan : EventComponent
    {
        private bool Initialize(EventPumper eventPumper)
        {
_EOF_

# Write classes to.
while IFS= read -d $'\0' -r file ; do
    CLASS=("$file")
	CLASS=${CLASS//*Services\// }
	CLASS=${CLASS//\.cs/}
	CLASS=${CLASS//\//.}
	CLASS=${CLASS// /}
	cat >> $TARGET << _EOF_
	        RegisterRoutines(new Services.$CLASS(eventPumper));
_EOF_
done < <(find ${SOURCE}/Services/ -type f -name "*.cs" -print0)

cat >> $TARGET << _EOF_
            return true;
        }
    }
}
_EOF_

echo [PreBuild.ScanService] Success.
