// This file is automatic generated by script.            
// DO NOT EDIT DIRECTLY.                                  
                                                          
using System;                                             
using Konata.Events;                                      
                                                          
namespace Konata                                          
{                                                         
    public partial class ServiceMan : EventComponent      
    {                                                     
        private bool Initialize(EventPumper eventPumper)  
        {                                                 
            RegisterRoutines(new Services.FriendList.GetTroopListReqV2(eventPumper));     
            RegisterRoutines(new Services.FriendList.ModifyGroupCardReq(eventPumper));     
            RegisterRoutines(new Services.GrayUinPro.Check(eventPumper));     
            RegisterRoutines(new Services.Heartbeat.Alive(eventPumper));     
            RegisterRoutines(new Services.JsApiSvr.WebView.WhiteList(eventPumper));     
            RegisterRoutines(new Services.MessageSvc.PbDeleteMsg(eventPumper));     
            RegisterRoutines(new Services.MessageSvc.PbGetMsg(eventPumper));     
            RegisterRoutines(new Services.MessageSvc.PbSendMsg(eventPumper));     
            RegisterRoutines(new Services.MessageSvc.PushForceOffline(eventPumper));     
            RegisterRoutines(new Services.MessageSvc.PushNotify(eventPumper));     
            RegisterRoutines(new Services.MessageSvc.PushRead(eventPumper));     
            RegisterRoutines(new Services.MessageSvc.RequestPushStatus(eventPumper));     
            RegisterRoutines(new Services.OidbSvc.Oidb0x55c_1(eventPumper));     
            RegisterRoutines(new Services.OidbSvc.Oidb0x570_8(eventPumper));     
            RegisterRoutines(new Services.OidbSvc.Oidb0x8a0_0(eventPumper));     
            RegisterRoutines(new Services.OidbSvc.Oidb0x8a0_1(eventPumper));     
            RegisterRoutines(new Services.OidbSvc.Oidb0x8fc_2(eventPumper));     
            RegisterRoutines(new Services.OnlinePush.PbPushGroupMsg(eventPumper));     
            RegisterRoutines(new Services.PbMessageSvc.PbMessageWithDraw(eventPumper));     
            RegisterRoutines(new Services.PbMessageSvc.PbMsgReadReport(eventPumper));     
            RegisterRoutines(new Services.StatSvc.Register(eventPumper));     
            RegisterRoutines(new Services.Wtlogin.Login(eventPumper));     
            RegisterRoutines(new Services.Wtlogin.Trans_emp(eventPumper));     
            return true;                                  
        }                                                 
    }                                                     
}                                                         
