// This file is automatic generated by script.  
// DO NOT EDIT DIRECTLY.                        
                                                
using System;                                   
                                                
namespace Konata                                
{                                               
    public partial class Service                
    {                                           
        static bool TouchServices()             
        {                                       
            Service instance;                   
            instance = Services.FriendList.GetTroopListReqV2.Instance;        
            instance = Services.FriendList.ModifyGroupCardReq.Instance;        
            instance = Services.GrayUinPro.Check.Instance;        
            instance = Services.Heartbeat.Alive.Instance;        
            instance = Services.JsApiSvr.WebView.WhiteList.Instance;        
            instance = Services.MessageSvc.PbDeleteMsg.Instance;        
            instance = Services.MessageSvc.PbGetMsg.Instance;        
            instance = Services.MessageSvc.PbSendMsg.Instance;        
            instance = Services.MessageSvc.PushForceOffline.Instance;        
            instance = Services.MessageSvc.PushNotify.Instance;        
            instance = Services.MessageSvc.PushRead.Instance;        
            instance = Services.MessageSvc.RequestPushStatus.Instance;        
            instance = Services.OidbSvc.Oidb0x55c_1.Instance;        
            instance = Services.OidbSvc.Oidb0x570_8.Instance;        
            instance = Services.OidbSvc.Oidb0x8a0_0.Instance;        
            instance = Services.OidbSvc.Oidb0x8a0_1.Instance;        
            instance = Services.OidbSvc.Oidb0x8fc_2.Instance;        
            instance = Services.OnlinePush.PbPushGroupMsg.Instance;        
            instance = Services.PbMessageSvc.PbMessageWithDraw.Instance;        
            instance = Services.PbMessageSvc.PbMsgReadReport.Instance;        
            instance = Services.StatSvc.Register.Instance;        
            instance = Services.Wtlogin.Login.Instance;        
            instance = Services.Wtlogin.Trans_emp.Instance;        
            return true;                        
        }                                       
    }                                           
}                                               
