// This file is automatic generated by script.  
// DO NOT EDIT DIRECTLY.   

using System;
using Konata.Utils.Protobuf;

namespace Konata.Core.Packet.Oidb.OidbModel
{
    public abstract class OidbCmd0x88d : OidbSSOPkg
    {
        internal OidbCmd0x88d(uint svcType, ReqBody reqBody)

            : base(0x88d, svcType, null, (ProtoTreeRoot root) =>
            {
                root.AddTree(reqBody?.BuildTree());
            })
        {

        }

        public class GroupExInfoOnly : OidbStruct
        {
            // 0x08
            public uint? tribe_id;

            // 0x10
            public uint? money_for_add_group;

            public override void Write(ProtoTreeRoot root)
            {
                root.AddLeafVar("08", tribe_id);
                root.AddLeafVar("10", money_for_add_group);
            }
        }

        public class GroupGeoInfo : OidbStruct
        {
            // 0x08
            public long? owneruin;

            // 0x10
            public uint? settime;

            // 0x18
            public uint? cityid;

            // 0x20
            public long? longitude;

            // 0x28
            public long? latitude;

            // 0x32
            public byte[] geocontent;

            // 0x38
            public long? poi_id;

            public override void Write(ProtoTreeRoot root)
            {
                root.AddLeafVar("08", owneruin);
                root.AddLeafVar("10", settime);
                root.AddLeafVar("18", cityid);
                root.AddLeafVar("20", longitude);
                root.AddLeafVar("28", latitude);
                root.AddLeafBytes("32", geocontent);
                root.AddLeafVar("38", poi_id);
            }
        }

        public class GroupHeadPortrait : OidbStruct
        {
            // 0x08
            public uint? pic_cnt;

            // 0x12
            public GroupHeadPortraitInfo rpt_msg_info;

            // 0x18
            public uint? default_id;

            // 0x20
            public uint? verifying_pic_cnt;

            // 0x2A 
            public GroupHeadPortraitInfo rpt_msg_verifyingpic_info;

            public override void Write(ProtoTreeRoot root)
            {
                root.AddLeafVar("08", pic_cnt);
                root.AddTree("12", rpt_msg_info?.BuildTree());
                root.AddLeafVar("18", default_id);
                root.AddLeafVar("20", verifying_pic_cnt);
                root.AddTree("2A", rpt_msg_verifyingpic_info?.BuildTree());
            }
        }

        public class GroupHeadPortraitInfo : OidbStruct
        {
            // 0x08
            public uint? pic_id;

            // 0x10
            public uint? left_x;

            // 0x18
            public uint? left_y;

            // 0x20
            public uint? right_x;

            // 0x28
            public uint? right_y;

            public override void Write(ProtoTreeRoot root)
            {
                root.AddLeafVar("08", pic_id);
                root.AddLeafVar("10", left_x);
                root.AddLeafVar("18", left_y);
                root.AddLeafVar("20", right_x);
                root.AddLeafVar("28", right_y);
            }
        }

        public class GroupInfo : OidbStruct
        {
            // 0x08
            public long? group_owner;

            // 0x10
            public uint? group_create_time;

            // 0x18
            public uint? group_flag;

            // 0x20
            public uint? group_flag_ext;

            // 0x28
            public uint? group_member_max_num;

            // 0x30
            public uint? group_member_num;

            // 0x38
            public uint? group_option;

            // 0x40
            public uint? group_class_ext;

            // 0x48
            public uint? group_special_class;

            // 0x50
            public uint? group_level;

            // 0x58
            public uint? group_face;

            // 0x60
            public uint? group_default_page;

            // 0x68
            public uint? group_info_seq;

            // 0x70
            public uint? group_roaming_time;

            // 0x7A
            public string group_name;

            // 0x8201
            public string group_memo;

            // 0x8A01
            public string group_finger_memo;

            // 0x9201
            public string group_class_text;

            // 0x9801
            public uint? group_alliance_code;

            // 0xA001
            public uint? group_extra_adm_num;

            // 0xA801
            public long? group_uin;

            // 0xB001
            public uint? group_cur_msg_seq;

            // 0xB801
            public uint? group_last_msg_time;

            // 0xC201
            public string group_question;

            // 0xCA01
            public string group_answer;

            // 0xD001
            public uint? group_visitor_max_num;

            // 0xD801
            public uint? group_visitor_cur_num;

            // 0xE001
            public uint? level_name_seq;

            // 0xE801
            public uint? group_admin_max_num;

            // 0xF001
            public uint? group_aio_skin_timestamp;

            // 0xF801
            public uint? group_board_skin_timestamp;

            // 0x8202
            public string group_aio_skin_url;

            // 0x8A02
            public string group_board_skin_url;

            // 0x9002
            public uint? group_cover_skin_timestamp;

            // 0x9A02
            public string group_cover_skin_url;

            // 0xA002
            public uint? group_grade;

            // 0xA802
            public uint? active_member_num;

            // 0xB002
            public uint? certification_type;

            // 0xBA02
            public string certification_text;

            // 0xC202
            public string group_rich_finger_memo;

            // 0xCA02
            public TagRecord rpt_tag_record;

            // 0xD202
            public GroupGeoInfo group_geo_info;

            // 0xD802
            public uint? head_portrait_seq;

            // 0xE202
            public GroupHeadPortrait msg_head_portrait;

            // 0xE802
            public uint? shutup_timestamp;

            // 0xF002
            public uint? shutup_timestamp_me;

            // 0xF802
            public uint? create_source_flag;

            // 0x8003
            public uint? cmduin_msg_seq;

            // 0x8803
            public uint? cmduin_join_time;

            // 0x9003
            public uint? cmduin_uin_flag;

            // 0x9803
            public uint? cmduin_flag_ex;

            // 0xA003
            public uint? cmduin_new_mobile_flag;

            // 0xA803
            public uint? cmduin_read_msg_seq;

            // 0xB003
            public uint? cmduin_last_msg_time;

            // 0xB803
            public uint? group_type_flag;

            // 0xC003
            public uint? app_privilege_flag;

            // 0xCA03
            public GroupExInfoOnly st_group_ex_info;

            // 0xD003
            public uint? group_sec_level;

            // 0xD803
            public uint? group_sec_level_info;

            // 0xE003
            public uint? cmduin_privilege;

            // 0xEA03
            public string poid_info;

            // 0xF003
            public uint? cmduin_flag_ex2;

            // 0xF803
            public long? conf_uin;

            // 0x8004
            public uint? conf_max_msg_seq;

            // 0x8804
            public uint? conf_to_group_time;

            // 0x9004
            public uint? password_redbag_time;

            // 0x9804
            public long? subscription_uin;

            // 0xA004
            public uint? member_list_change_seq;

            // 0xA804
            public uint? membercard_seq;

            // 0xB004
            public long? root_id;

            // 0xB804
            public long? parent_id;

            // 0xC004
            public uint? team_seq;

            // 0xC804
            public long? history_msg_begin_time;

            // 0xD004
            public long? invite_no_auth_num_limit;

            // 0xD804
            public uint? cmduin_history_msg_seq;

            // 0xE004
            public uint? cmduin_join_msg_seq;

            // 0xE804
            public uint? group_flagext3;

            // 0xF004
            public uint? group_open_appid;

            // 0xF804
            public uint? is_conf_group;

            // 0x8005
            public uint? is_modify_conf_group_face;

            // 0x8805
            public uint? is_modify_conf_group_name;

            // 0x9005
            public uint? no_finger_open_flag;

            // 0x9805
            public uint? no_code_finger_open_flag;

            // 0xA005
            public uint? auto_agree_join_group_user_num_for_normal_group;

            // 0xA805
            public uint? auto_agree_join_group_user_num_for_conf_group;

            // 0xB005
            public uint? is_allow_conf_group_member_nick;

            // 0xB805
            public uint? is_allow_conf_group_member_at_all;

            // 0xC005
            public uint? is_allow_conf_group_member_modify_group_name;

            // 0xCA05
            public string long_group_name;

            // 0xD005
            public uint? cmduin_join_real_msg_seq;

            // 0xD805
            public uint? is_group_freeze;

            // 0xE005
            public uint? msg_limit_frequency;

            // 0xEA05
            public byte[] join_group_auth;

            // 0xF005
            public uint? hl_guild_appid;

            // 0xF805
            public uint? hl_guild_sub_type;

            // 0x8006
            public uint? hl_guild_orgid;

            // 0x8806
            public uint? is_allow_hl_guild_binary;

            // 0x9006
            public uint? cmduin_ringtone_id;

            // 0x9806
            public uint? group_flagext4;

            // 0xA006
            public uint? group_freeze_reason;

            // 0xA806
            public uint? is_allow_recall_msg;

            public override void Write(ProtoTreeRoot root)
            {
                root.AddLeafVar("08", group_owner);
                root.AddLeafVar("10", group_create_time);
                root.AddLeafVar("18", group_flag);
                root.AddLeafVar("20", group_flag_ext);
                root.AddLeafVar("28", group_member_max_num);
                root.AddLeafVar("30", group_member_num);
                root.AddLeafVar("38", group_option);
                root.AddLeafVar("40", group_class_ext);
                root.AddLeafVar("48", group_special_class);
                root.AddLeafVar("50", group_level);
                root.AddLeafVar("58", group_face);
                root.AddLeafVar("60", group_default_page);
                root.AddLeafVar("68", group_info_seq);
                root.AddLeafVar("70", group_roaming_time);
                root.AddLeafString("7A", group_name);
                root.AddLeafString("8201", group_memo);
                root.AddLeafString("8A01", group_finger_memo);
                root.AddLeafString("9201", group_class_text);
                root.AddLeafVar("9801", group_alliance_code);
                root.AddLeafVar("A001", group_extra_adm_num);
                root.AddLeafVar("A801", group_uin);
                root.AddLeafVar("B001", group_cur_msg_seq);
                root.AddLeafVar("B801", group_last_msg_time);
                root.AddLeafString("C201", group_question);
                root.AddLeafString("CA01", group_answer);
                root.AddLeafVar("D001", group_visitor_max_num);
                root.AddLeafVar("D801", group_visitor_cur_num);
                root.AddLeafVar("E001", level_name_seq);
                root.AddLeafVar("E801", group_admin_max_num);
                root.AddLeafVar("F001", group_aio_skin_timestamp);
                root.AddLeafVar("F801", group_board_skin_timestamp);
                root.AddLeafString("8202", group_aio_skin_url);
                root.AddLeafString("8A02", group_board_skin_url);
                root.AddLeafVar("9002", group_cover_skin_timestamp);
                root.AddLeafString("9A02", group_cover_skin_url);
                root.AddLeafVar("A002", group_grade);
                root.AddLeafVar("A802", active_member_num);
                root.AddLeafVar("B002", certification_type);
                root.AddLeafString("BA02", certification_text);
                root.AddLeafString("C202", group_rich_finger_memo);
                root.AddTree("CA02", rpt_tag_record?.BuildTree());
                root.AddTree("D202", group_geo_info?.BuildTree());
                root.AddLeafVar("D802", head_portrait_seq);
                root.AddTree("E202", msg_head_portrait?.BuildTree());
                root.AddLeafVar("E802", shutup_timestamp);
                root.AddLeafVar("F002", shutup_timestamp_me);
                root.AddLeafVar("F802", create_source_flag);
                root.AddLeafVar("8003", cmduin_msg_seq);
                root.AddLeafVar("8803", cmduin_join_time);
                root.AddLeafVar("9003", cmduin_uin_flag);
                root.AddLeafVar("9803", cmduin_flag_ex);
                root.AddLeafVar("A003", cmduin_new_mobile_flag);
                root.AddLeafVar("A803", cmduin_read_msg_seq);
                root.AddLeafVar("B003", cmduin_last_msg_time);
                root.AddLeafVar("B803", group_type_flag);
                root.AddLeafVar("C003", app_privilege_flag);
                root.AddTree("CA03", st_group_ex_info?.BuildTree());
                root.AddLeafVar("D003", group_sec_level);
                root.AddLeafVar("D803", group_sec_level_info);
                root.AddLeafVar("E003", cmduin_privilege);
                root.AddLeafString("EA03", poid_info);
                root.AddLeafVar("F003", cmduin_flag_ex2);
                root.AddLeafVar("F803", conf_uin);
                root.AddLeafVar("8004", conf_max_msg_seq);
                root.AddLeafVar("8804", conf_to_group_time);
                root.AddLeafVar("9004", password_redbag_time);
                root.AddLeafVar("9804", subscription_uin);
                root.AddLeafVar("A004", member_list_change_seq);
                root.AddLeafVar("A804", membercard_seq);
                root.AddLeafVar("B004", root_id);
                root.AddLeafVar("B804", parent_id);
                root.AddLeafVar("C004", team_seq);
                root.AddLeafVar("C804", history_msg_begin_time);
                root.AddLeafVar("D004", invite_no_auth_num_limit);
                root.AddLeafVar("D804", cmduin_history_msg_seq);
                root.AddLeafVar("E004", cmduin_join_msg_seq);
                root.AddLeafVar("E804", group_flagext3);
                root.AddLeafVar("F004", group_open_appid);
                root.AddLeafVar("F804", is_conf_group);
                root.AddLeafVar("8005", is_modify_conf_group_face);
                root.AddLeafVar("8805", is_modify_conf_group_name);
                root.AddLeafVar("9005", no_finger_open_flag);
                root.AddLeafVar("9805", no_code_finger_open_flag);
                root.AddLeafVar("A005", auto_agree_join_group_user_num_for_normal_group);
                root.AddLeafVar("A805", auto_agree_join_group_user_num_for_conf_group);
                root.AddLeafVar("B005", is_allow_conf_group_member_nick);
                root.AddLeafVar("B805", is_allow_conf_group_member_at_all);
                root.AddLeafVar("C005", is_allow_conf_group_member_modify_group_name);
                root.AddLeafString("CA05", long_group_name);
                root.AddLeafVar("D005", cmduin_join_real_msg_seq);
                root.AddLeafVar("D805", is_group_freeze);
                root.AddLeafVar("E005", msg_limit_frequency);
                root.AddLeafBytes("EA05", join_group_auth);
                root.AddLeafVar("F005", hl_guild_appid);
                root.AddLeafVar("F805", hl_guild_sub_type);
                root.AddLeafVar("8006", hl_guild_orgid);
                root.AddLeafVar("8806", is_allow_hl_guild_binary);
                root.AddLeafVar("9006", cmduin_ringtone_id);
                root.AddLeafVar("9806", group_flagext4);
                root.AddLeafVar("A006", group_freeze_reason);
                root.AddLeafVar("A806", is_allow_recall_msg);
            }
        }

        public class ReqBody : OidbStruct
        {
            // 0x08
            public uint? appid;

            // 0x12
            public ReqGroupInfo stzreqgroupinfo;

            // 0x18
            public uint? pc_client_version;

            public override void Write(ProtoTreeRoot root)
            {
                root.AddLeafVar("08", appid);
                root.AddTree("12", stzreqgroupinfo?.BuildTree());
                root.AddLeafVar("18", pc_client_version);
            }
        }

        public class ReqGroupInfo : OidbStruct
        {
            // 0x08
            public long? group_code;

            // 0x12
            public GroupInfo stgroupinfo;

            // 0x18
            public uint? last_get_group_name_time;

            public override void Write(ProtoTreeRoot root)
            {
                root.AddLeafVar("08", group_code);
                root.AddTree("12", stgroupinfo?.BuildTree());
                root.AddLeafVar("18", last_get_group_name_time);
            }
        }

        public class RspBody : OidbStruct
        {
            // 0x0A
            public RspGroupInfo stzrspgroupinfo;

            // 0x12
            public byte[] str_errorinfo;

            public override void Write(ProtoTreeRoot root)
            {
                root.AddTree("0A", stzrspgroupinfo?.BuildTree());
                root.AddLeafBytes("12", str_errorinfo);
            }
        }

        public class RspGroupInfo : OidbStruct
        {
            // 0x08
            public long? group_code;

            // 0x10
            public uint? result;

            // 0x1A
            public RspGroupInfo stgroupinfo;

            public override void Write(ProtoTreeRoot root)
            {
                root.AddLeafVar("08", group_code);
                root.AddLeafVar("10", result);
                root.AddTree("1A", stgroupinfo?.BuildTree());
            }
        }

        public class TagRecord : OidbStruct
        {
            // 0x08
            public long? from_uin;

            // 0x10
            public long? group_code;

            // 0x1A
            public byte[] tag_id;

            // 0x20
            public long? set_time;

            // 0x28
            public uint? good_num;

            // 0x30
            public uint? bad_num;

            // 0x38
            public uint? tag_len;

            // 0x42
            public byte[] tag_value;

            public override void Write(ProtoTreeRoot root)
            {
                root.AddLeafVar("08", from_uin);
                root.AddLeafVar("10", group_code);
                root.AddLeafBytes("1A", tag_id);
                root.AddLeafVar("20", set_time);
                root.AddLeafVar("28", good_num);
                root.AddLeafVar("30", bad_num);
                root.AddLeafVar("38", tag_len);
                root.AddLeafBytes("42", tag_value);
            }
        }
    }
}
