name: Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    # Checkout
    steps:
    - uses: actions/checkout@v3
    
    # Setup
    - name: Setup Test
      uses: actions/setup-dotnet@v3
    
    # Restore packages
    - name: Restore dependencies
      run: dotnet restore
      
    # Test
    - name: Test
      run: dotnet test
